export const SERIES_NAMES_DE: Record<string, string> = {
  'Mega Evolution':          'Mega-Entwicklung',
  'Scarlet & Violet':        'Karmesin & Purpur',
  'Sword & Shield':          'Schwert & Schild',
  'Sun & Moon':              'Sonne & Mond',
  'XY':                      'XY',
  'Black & White':           'Schwarz & Weiß',
  'HeartGold & SoulSilver':  'HeartGold & SoulSilver',
  'Platinum':                'Platin',
  'Diamond & Pearl':         'Diamant & Perl',
  'EX':                      'EX',
  'E-Card':                  'e-Card',
  'Neo':                     'Neo',
  'Gym':                     'Gym',
  'Base':                    'Basis',
  'Other':                   'Sonstige',
  'POP':                     'POP',
};

const SET_NAMES_DE: Record<string, string> = {
  // ── Mega-Entwicklung ─────────────────────────────────────────────────────
  'me1':       'Mega-Entwicklung',
  'me2':       'Fatale Flammen',
  'me2pt5':    'Erhabene Helden',
  'me3':       'Optimale Ordnung',
  'me4':       'Wachsendes Chaos',

  // ── Karmesin & Purpur ────────────────────────────────────────────────────
  'sv1':       'Karmesin & Purpur',
  'sv2':       'Entwicklungen in Paldea',
  'sv3':       'Obsidianflammen',
  'sv3pt5':    '151',
  'sv4':       'Paradoxrift',
  'sv4pt5':    'Paldeas Schicksale',
  'sv5':       'Gewalten der Zeit',
  'sv6':       'Maskerade im Zwielicht',
  'sv6pt5':    'Nebel der Sagen',
  'sv7':       'Stellarkrone',
  'sv8':       'Stürmische Funken',
  'sv8pt5':    'Prismatische Entwicklungen',
  'sv9':       'Reisegefährten',
  'sv10':      'Ewige Rivalen',
  'rsv10pt5':  'Weiße Flammen',
  'zsv10pt5':  'Schwarze Blitze',
  'sve':       'Karmesin & Purpur Energien',
  'svp':       'K&P Black Star Promos',

  // ── Schwert & Schild ─────────────────────────────────────────────────────
  'swsh1':     'Schwert & Schild',
  'swsh2':     'Sturm des Rebellen',
  'swsh3':     'Dunkelheit der Glut',
  'swsh35':    'Pfad des Champions',
  'swsh4':     'Lebendige Elektrizität',
  'swsh45':    'Strahlende Geheimnisse',
  'swsh45sv':  'Strahlende Geheimnisse – Shiny Vault',
  'swsh5':     'Kampfstile',
  'swsh6':     'Eisige Herrschaft',
  'swsh7':     'Evolving Skies',
  'swsh8':     'Fusionsangriff',
  'swsh9':     'Brillante Sterne',
  'swsh10':    'Astralglanz',
  'swsh10tg':  'Astralglanz Trainer-Galerie',
  'swsh11':    'Verlorener Ursprung',
  'swsh11tg':  'Verlorener Ursprung Trainer-Galerie',
  'swsh12':    'Silberner Sturm',
  'swsh12tg':  'Silberner Sturm Trainer-Galerie',
  'swsh12pt5': 'Zenit des Königs',
  'swsh12pt5gg': 'Zenit des Königs – Galar-Galerie',
  'cel25':     'Feierlichkeiten',
  'cel25c':    'Feierlichkeiten – Klassische Kollektion',
  'pgo':       'Pokémon GO',
  'swshp':     'S&S Black Star Promos',
  'mcd21':     "McDonald's Kollektion 2021",
  'mcd22':     "McDonald's Kollektion 2022",
  'fut20':     'Pokémon Futsal Kollektion',

  // ── Sonne & Mond ─────────────────────────────────────────────────────────
  'sm1':       'Sonne & Mond',
  'sm2':       'Wächter des Aufgehenden Mondlichts',
  'sm3':       'Brennende Schatten',
  'sm35':      'Schimmernde Legenden',
  'sm4':       'Karmesinrote Invasion',
  'sm5':       'Ultra-Prisma',
  'sm6':       'Verbotenes Licht',
  'sm7':       'Himmlischer Sturm',
  'sm75':      'Drachenhoheit',
  'sm8':       'Verlorener Donner',
  'sm9':       'Teamwork',
  'sm10':      'Unzerbrechliche Bande',
  'sm11':      'Eintracht der Geister',
  'sm115':     'Verborgene Schicksale',
  'sm12':      'Kosmische Finsternis',
  'sma':       'Verborgene Schicksale – Shiny Vault',
  'det1':      'Meisterdetektiv Pikachu',
  'smp':       'Sonne & Mond Promos',
  'mcd17':     "McDonald's Kollektion 2017",
  'mcd18':     "McDonald's Kollektion 2018",
  'mcd19':     "McDonald's Kollektion 2019",

  // ── XY ───────────────────────────────────────────────────────────────────
  'xy0':       'Kalos Starter-Set',
  'xy1':       'XY',
  'xy2':       'Fackelglut',
  'xy3':       'Rasende Fäuste',
  'xy4':       'Phantomkräfte',
  'xy5':       'Urknall',
  'xy6':       'Tosende Himmel',
  'xy7':       'Antike Ursprünge',
  'xy8':       'Durchbruch',
  'xy9':       'Wendepunkt',
  'xy10':      'Schicksale Vereint',
  'xy11':      'Dampfkessel',
  'xy12':      'Entwicklungen',
  'g1':        'Generationen',
  'dc1':       'Doppelkrise',
  'xyp':       'XY Black Star Promos',
  'mcd14':     "McDonald's Kollektion 2014",
  'mcd15':     "McDonald's Kollektion 2015",
  'mcd16':     "McDonald's Kollektion 2016",

  // ── Schwarz & Weiß ───────────────────────────────────────────────────────
  'bw1':       'Schwarz & Weiß',
  'bw2':       'Neue Kräfte',
  'bw3':       'Edle Siege',
  'bw4':       'Nächste Schicksale',
  'bw5':       'Dunkle Entdecker',
  'bw6':       'Drachen-Erwachen',
  'bw7':       'Grenzenlose Kräfte',
  'bw8':       'Plasmasturm',
  'bw9':       'Plasmafrost',
  'bw10':      'Plasmawende',
  'bw11':      'Legendäre Schätze',
  'dv1':       'Drachentresor',
  'bwp':       'S&W Black Star Promos',
  'mcd11':     "McDonald's Kollektion 2011",
  'mcd12':     "McDonald's Kollektion 2012",

  // ── HeartGold & SoulSilver ───────────────────────────────────────────────
  'hgss1':     'HeartGold & SoulSilver',
  'hgss2':     'HS—Entfesselt',
  'hgss3':     'HS—Unerschrocken',
  'hgss4':     'HS—Triumphierend',
  'col1':      'Ruf der Legenden',
  'hsp':       'HGSS Black Star Promos',
  'ru1':       'Pokémon Rumble',

  // ── Platin ───────────────────────────────────────────────────────────────
  'pl1':       'Platin',
  'pl2':       'Aufstrebende Rivalen',
  'pl3':       'Absolute Sieger',
  'pl4':       'Arceus',

  // ── Diamant & Perl ───────────────────────────────────────────────────────
  'dp1':       'Diamant & Perl',
  'dp2':       'Geheimnisvolle Schätze',
  'dp3':       'Geheimnisvolle Welten',
  'dp4':       'Große Begegnungen',
  'dp5':       'Majestätische Dämmerung',
  'dp6':       'Die Erwachten Legenden',
  'dp7':       'Sturmfront',
  'dpp':       'DP Black Star Promos',

  // ── EX ───────────────────────────────────────────────────────────────────
  'ex1':       'Rubin & Saphir',
  'ex2':       'Sandsturm',
  'ex3':       'Drachen',
  'ex4':       'Team Magma vs. Team Aqua',
  'ex5':       'Verborgene Legenden',
  'ex6':       'Feuerrot & Blattgrün',
  'ex7':       'Team Rocket kehrt zurück',
  'ex8':       'Deoxys',
  'ex9':       'Smaragd',
  'ex10':      'Unsichtbare Kräfte',
  'ex11':      'Deltaart',
  'ex12':      'Schöpfer der Legenden',
  'ex13':      'Holon Phantome',
  'ex14':      'Kristallwächter',
  'ex15':      'Drachengrenzen',
  'ex16':      'Krafthüter',
  'tk1a':      'EX Trainer-Kit Latias',
  'tk1b':      'EX Trainer-Kit Latios',
  'tk2a':      'EX Trainer-Kit 2 Plusle',
  'tk2b':      'EX Trainer-Kit 2 Minun',

  // ── e-Card ───────────────────────────────────────────────────────────────
  'ecard1':    'Expedition',
  'ecard2':    'Aquapolis',
  'ecard3':    'Skyridge',

  // ── Neo ──────────────────────────────────────────────────────────────────
  'neo1':      'Neo Genesis',
  'neo2':      'Neo Entdeckung',
  'neo3':      'Neo Revelation',
  'neo4':      'Neo Schicksal',

  // ── Gym ──────────────────────────────────────────────────────────────────
  'gym1':      'Gym Helden',
  'gym2':      'Gym Herausforderer',

  // ── Basis ────────────────────────────────────────────────────────────────
  'base1':     'Basisset',
  'base2':     'Dschungel',
  'base3':     'Fossil',
  'base4':     'Basisset 2',
  'base5':     'Team Rocket',
  'base6':     'Legendäre Kollektion',
  'basep':     'Wizards Black Star Promos',
  'si1':       'Südliche Inseln',
  'bp':        'Best of Game',
  'np':        'Nintendo Black Star Promos',
};

export function getSetNameDe(setId: string, fallback: string): string {
  return SET_NAMES_DE[setId] ?? fallback;
}
