const SET_NAMES_DE: Record<string, string> = {
  // Scarlet & Violet
  'sv1':      'Karmesin & Purpur',
  'sv2':      'Entwicklungen in Paldea',
  'sv3':      'Obsidianflammen',
  'sv3pt5':   '151',
  'sv4':      'Paradoxrift',
  'sv4pt5':   'Schicksalsgabe',
  'sv5':      'Temporale Kräfte',
  'sv6':      'Maskerade im Zwielicht',
  'sv6pt5':   'Verblassende Sagen',
  'sv7':      'Sternenglanz',
  'sv7pt5':   'Stellar Crown',
  'sv8':      'Brausende Funken',
  'sv8pt5':   'Prismatische Entwicklungen',
  'sv9':      'Reisende der Lüfte',
  // Sword & Shield
  'swsh1':    'Schwert & Schild',
  'swsh2':    'Sturm des Rebellen',
  'swsh3':    'Dunkelheit der Glut',
  'swsh35':   'Pfad des Champions',
  'swsh4':    'Lebendige Elektrizität',
  'swsh45':   'Schicksalsgabe',
  'swsh45sv': 'Shining Fates',
  'swsh5':    'Rasantes Tempo',
  'swsh6':    'Chilling Reign',
  'swsh7':    'Evolving Skies',
  'swsh75':   'Celebrations',
  'swsh8':    'Fusion Strike',
  'swsh9':    'Brillante Sterne',
  'swsh10':   'Astral Radiance',
  'swsh10tg': 'Pokémon GO',
  'swsh11':   'Lost Origin',
  'swsh12':   'Silver Tempest',
  'swsh12pt5':'Crown Zenith',
  // Sun & Moon
  'sm1':      'Sonne & Mond',
  'smp':      'Sonne & Mond Promos',
  'sm2':      'Wächter des Aufgehenden Mondlichts',
  'sm3':      'Brennende Schatten',
  'sm35':     'Shining Legends',
  'sm4':      'Schimmernde Legenden',
  'sm5':      'Ultra Prisma',
  'sm6':      'Verbotenes Licht',
  'sm7':      'Celestial Storm',
  'sm75':     'Dragon Majesty',
  'sm8':      'Lost Thunder',
  'sm9':      'Team Up',
  'sm10':     'Unbroken Bonds',
  'sm11':     'Unified Minds',
  'sm115':    'Hidden Fates',
  'sm12':     'Cosmic Eclipse',
  // XY
  'xy1':      'XY',
  'xy2':      'Flare Team',
  'xy3':      'Phantom Forces',
  'xy4':      'Primal Clash',
  'xy5':      'Roaring Skies',
  'xy6':      'Ancient Origins',
  'xy7':      'BREAKthrough',
  'xy8':      'BREAKpoint',
  'xy9':      'Fates Collide',
  'xy10':     'Steam Siege',
  'xy11':     'Evolutions',
  // Black & White
  'bw1':      'Black & White',
  'bw2':      'Emerging Powers',
  'bw3':      'Noble Victories',
  'bw4':      'Next Destinies',
  'bw5':      'Dark Explorers',
  'bw6':      'Dragons Exalted',
  'bw7':      'Boundaries Crossed',
  'bw8':      'Plasma Storm',
  'bw9':      'Plasma Freeze',
  'bw10':     'Plasma Blast',
  'bw11':     'Legendary Treasures',
  // Classic / Base
  'base1':    'Basisset',
  'base2':    'Dschungel',
  'basep':    'Baseset Promos',
  'base3':    'Fossil',
  'base4':    'Team Rocket',
  'base5':    'Gym Helden',
  'base6':    'Gym Herausforderer',
  'neo1':     'Neo Genesis',
  'neo2':     'Neo Entdeckung',
  'neo3':     'Neo Revelation',
  'neo4':     'Neo Schicksal',
  'ecard1':   'Expedition',
  'ecard2':   'Aquapolis',
  'ecard3':   'Skyridge',
};

export function getSetNameDe(setId: string, fallback: string): string {
  return SET_NAMES_DE[setId] ?? fallback;
}
